version: "2"

build:
  os: "ubuntu-22.04"
  apt_packages:
    - openjdk-21-jdk
  tools:
    python: "3.10"
  jobs:
    pre_build:
      - ./gradlew javadoc

python:
  install:
    - requirements: docs/docs/requirements.txt

sphinx:
  configuration: docs/docs/source/conf.py
