name: Docker Run Integration Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read
  checks: write

jobs:
  epicstests:
    name: Run all unit tests reliant on EPICS install
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
        fetch-depth: 0
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Create Build Reports Folder
      run: mkdir -p build/reports/tests
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        file: docker/Dockerfile
        cache-from: type=gha
        cache-to: type=gha,mode=max
    - name: Run tests with docker compose
      run: docker compose -f docker/docker-compose.epicsTests.yml run epicsarchiver-test
      env:
        DOCKER_DEFAULT_PLATFORM: linux/amd64
        COMPOSE_DOCKER_CLI_BUILD: 1
        DOCKER_BUILDKIT: 1
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3
      if: success() || failure() # always run even if the previous step fails
      with:
        report_paths: '**/build/test-results/epicsTests/TEST-*.xml'
    - name: Upload build reports
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: build-reports
        path: build/reports/
