name: Pull Request

on:
  pull_request:
    branches: ["*"]

concurrency:
  group: pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  verify:
    uses: ./.github/workflows/verify.yml
    permissions:
      contents: read
      checks: write

